### ISSUE TITLE
attempt to use pep-646 variadic generics for Row, Result, select(), others

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy2-stubs#1]
it's only in Python 3.10, the ability to make our own types that are like tuples:

https://www.python.org/dev/peps/pep-0646/

what we would want is:
```

stmt: Select[User, str, int]  = select(User, Address.name, Address.id).join_from(User, Address)

result: Result[User, str, int] = session.execute(stmt)

for row: Row[User, str, int] in result:
    # ...

```
that is, every ReturnsRows class as well as Result and Row become some kind of covariant variadic generic.   is that every word ?

**Comment by zzzeek** [comment]
here's from the original discussion for pep 646: https://github.com/python/typing/issues/193#issuecomment-235118887

**Comment by zzzeek** [comment]
superseded by https://github.com/sqlalchemy/sqlalchemy/issues/7516 for 2.0

**Comment by CaselIT** [comment]
we could have transfered it. I think we can just close this
