### ISSUE TITLE
Typing error in Index

### ISSUE THREAD

**Issue by rajinder-mohan** [sqlalchemy/sqlalchemy2-stubs#116]
When `Index` outside table
` error: Argument 3 to "Index" has incompatible type "ColumnElement[Any]"; expected "ColumnClause[Any]"`
When `Index` is inline
` error: Argument 2 to "Index" has incompatible type "str"; expected "ColumnClause[Any]"`

**Comment by MaicoTimmerman** [comment]
This should have been fixed in #108, which is released just now as version 0.0.2a2.
