### ISSUE TITLE
__version__ is missing in __init__.pyi

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy2-stubs#120]
**Describe the bug**
Mypy tells me that \_\_version__ doesn't exist for sqlalchemy, but it's just missing in the \_\_init__.pyi

**Expected behavior**
\_\_version__  should be defined

**To Reproduce**

```python
import sqlalchemy

print(sqlalchemy.__version__)
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.18
 - mypy: 0.902
 - SQLAlchemy2-stubs: 0.0.2a2

**Comment by CaselIT** [comment]
Thanks for reporting. If you could contribute a fix it would be great!

**Comment by kasium** [comment]
Sure, I'll do so :-)

**Comment by CaselIT** [comment]
thanks!
