### ISSUE TITLE
TypeDecorator.cache_ok is missing

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy2-stubs#123]
**Describe the bug**
`TypeDecorator.cache_ok` is missing in the stubs

**Expected behavior**
`TypeDecorator.cache_ok` is present

**To Reproduce**

```py

from sqlalchemy.types import TypeDecorator

class MyType(TypeDecorator):
  cache_ok = True
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.19
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a2

**Comment by CaselIT** [comment]
Thanks for reporting and providing a fix. I've left a comment on the pr
