### ISSUE TITLE
How to type Array of Enum?

### ISSUE THREAD

**Issue by b0g3r** [sqlalchemy/sqlalchemy2-stubs#130]
I cannot find the right typing for Array of Enums. It is also doesn't work with Array of Strings, so I haven't any workaround :(

**Example**
```python
import sqlalchemy as sa
import enum
from typing import List
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class TokenType(str, enum.Enum):
    a = "a"

class Model(Base):
    token_types: List[TokenType] = sa.Column(
        sa.ARRAY(sa.Enum(TokenType)),
        nullable=False,
    )

```
**Complete stack trace, if applicable**
```
app/models.py:305: error: [SQLAlchemy Mypy plugin] Left hand assignment
'token_types: "List[TokenType]"' not compatible with ORM mapped expression of
type "Mapped[List[_TE]]"  [misc]
        token_types: List[TokenType] = sa.Column(
```

**Versions**
 - OS: Big Sure 11.4
 - Python: 3.8
 - SQLAlchemy: 1.4.20
 - mypy: 0.902
 - SQLAlchemy2-stubs: 0.0.2a4

**Comment by mdczaplicki** [comment]
Don't use SQLAlchemy generic `ARRAY`. Use the one designed for you dialect. E.g. for Postgres:
```
from sqlalchemy.dialects.postgresql import ARRAY
```

**Comment by phillipuniverse** [comment]
Thanks @mdczaplicki, confirmed that this fixed my issue.

**Comment by phillipuniverse** [comment]
@b0g3r shouldn’t the generic non-dialect-specific version also be type-hinted?

**Comment by b0g3r** [comment]
@phillipuniverse I think it requires different issue, problem from this issue is solved by workaround. I independently started using posgtres specific arrays, so I could use postgres specific operations on array fields
