### ISSUE TITLE
Non nullable fields are treated like Optional

### ISSUE THREAD

**Issue by mdczaplicki** [sqlalchemy/sqlalchemy2-stubs#135]
**Describe the bug**
Non nullable columns are treated as optional.

**Expected behavior**
Non nullable columns are treated as non optional.

**To Reproduce**

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy.orm import declarative_base

Base = declarative_base(metadata=MetaData())


class U(Base):
    __tablename__ = "x"
    id = Column(Integer, primary_key=True)
    my_int = Column(Integer, nullable=False, index=True)


def x(my_int: int):
  pass

u1 = U(my_int = 2)

x(u1.my_int)
```

**Error**

```
error: Argument 1 to "x" has incompatible type "Optional[int]"; expected "int"
```

**Versions.**
 - OS: Linux Mint 19
 - Python: 3.7.10
 - SQLAlchemy: 1.4.22
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a4 & 0.0.2a6

**Additional context**
Trying to test on 

- [x] 0.0.2a6

Seems to work when you manually type `my_int: int = Column(Integer, nullable=False, index=True)`

**Have a nice day!**

**Comment by zzzeek** [comment]
this is expected behavior for the moment:

https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html#introspection-of-columns-based-on-typeengine

> The types are by default always considered to be Optional, even for the primary key and non-nullable column. The reason is because while the database columns “id” and “name” can’t be NULL, the Python attributes id and name most certainly can be None without an explicit constructor:
```py
>>> m1 = MyClass()
>>> m1.id
None
```
> The types of the above columns can be stated explicitly, providing the two advantages of clearer self-documentation as well as being able to control which types are optional:

therefore:

```py
class U(Base):
    __tablename__ = "x"
    id = Column(Integer, primary_key=True)
    my_int : int = Column(Integer, nullable=False, index=True)

```

**Comment by mdczaplicki** [comment]
Thanks, a little counterintuitive, but logical I guess.
