### ISSUE TITLE
scoped_session __call__ returns Any

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy2-stubs#136]
**Describe the bug**
Calling scoped_session returns Any which is should not be the case

**Expected behavior**
A concrete type should be returned

**To Reproduce**
```py
session_factory = sessionmaker(bind=create_engine("foo", future=True))
reveal_type(scoped_session(session_factory)())
```

**Error**
```
Revealed type is "Any"
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.22
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a6

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. If you could provide a pr it would be great

**Comment by kasium** [comment]
I can give it a try
