### ISSUE TITLE
Incorrect typing (or too generic) for `Subquery.c` or `Table.c`

### ISSUE THREAD

**Issue by mdczaplicki** [sqlalchemy/sqlalchemy2-stubs#142]
**Describe the bug**
Mypy complains about missing attribute or incompatible types in assignment.

**Expected behavior**
Mypy not complaining

**To Reproduce**
```py
x = Table("x", metadata, Column("aaa", Integer, primary_key=True))
sq = select(x).subquery()
columns: ColumnCollection = sq.c if sq else x.c  # either add or remove typing to see one of two errors
columns.aaa
```

**Error**

```
Incompatible types in assignment (expression has type "object", variable has type "ColumnCollection[Any]")
"object" has no attribute "aaa"
```

**Versions.**
 - OS: Linux Mint 20.1
 - Python: 3.7.10
 - SQLAlchemy: 1.4.22
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a6

**Additional context**
Happens after upgrading from `0.0.2a4` to `0.0.2a6`

**Have a nice day!**

**Comment by CaselIT** [comment]
This is working as expected. The issue is that you cannot do `sq.c if sq else x.c`, since you will get `TypeError: Boolean value of this clause is not defined`, you need to do `sq.c if sq is not None else x.c`.

Sadly mypy error is not clear in this case

**Comment by mdczaplicki** [comment]
Actually never got this error :stuck_out_tongue: .
