### ISSUE TITLE
op() incorrectly returns ClauseElement

### ISSUE THREAD

**Issue by andersk** [sqlalchemy/sqlalchemy2-stubs#148]
**Describe the bug**

`column("flags").op("&")(1)` or `column("flags", Integer).op("&", return_type=Integer)(1)` is inferred as `ClauseElement`.

**Expected behavior**
This should be `BinaryExpression[Integer]`.

**To Reproduce**

```py
from sqlalchemy.sql import column, ColumnElement
from sqlalchemy.types import Integer

bit: "ColumnElement[Integer]" = column("flags", Integer).op("&", return_type=Integer)(1)
```

**Error**

```
test.py:4: error: Incompatible types in assignment (expression has type "ClauseElement", variable has type "ColumnElement[Integer]")  [assignment]
```

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.6.9
 - SQLAlchemy: 1.4.22
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a8

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
released as https://github.com/sqlalchemy/sqlalchemy2-stubs/releases/tag/v0.0.2a10
