### ISSUE TITLE
Asynchronous sessionmaker initialization type error

### ISSUE THREAD

**Issue by r4rdsn** [sqlalchemy/sqlalchemy2-stubs#155]
**Describe the bug**
mypy fails on asynchronous sessionmaker initialization.

**Expected behavior**
No errors.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
import os

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import sessionmaker

engine = create_async_engine(os.getenv("DATABASE_URL"))
async_session = sessionmaker(engine, class_=AsyncSession)
```

**Error**

```
session.py:8: error: Value of type variable "_TSessionMakerType" of "sessionmaker" cannot be "AsyncSession"
Found 1 error in 1 file (checked 1 source file)
```

**Versions.**
 - OS: Linux
 - Python: 3.9.6
 - SQLAlchemy: 1.4.23
 - mypy: 0.910
 - SQLAlchemy2-stubs: v0.0.2a9

**Additional context**
The problem appeared on the latest release of sqlalchemy2-stubs and was not present on v0.0.2a8.

**Have a nice day!**

**Comment by CaselIT** [comment]
Thanks for the report

**Comment by joaosr** [comment]
Same happening for me.

**Comment by CaselIT** [comment]
released as v0.0.2a10

**Comment by mjpieters** [comment]
This appears to have regressed? I'm using version 0.0.2a27, and the example in this issue now produces:

```
Argument of type "Type[AsyncSession]" cannot be assigned to parameter "class_" of type "Type[_TSessionMakerType@sessionmaker]" in function "__init__"
  Type "Type[AsyncSession]" cannot be assigned to type "Type[_TSessionMakerType@sessionmaker]"
```

when using Pyright.

**Comment by mjpieters** [comment]
Downgrading to `sqlalchemy2-stubs==0.0.2.a26` fixed this issue; I'll make this a separate report.

**Comment by zzzeek** [comment]
@mjpieters I am hoping 2.0 betas are very soon.  that's where these issues if you have them will be permanently fixed so i hope you have time to test a bit.

**Comment by mjpieters** [comment]
Yeah, I can't find a release of sqlalchemy2-stubs that actually makes the example work, so it's probably a pyright incompatibility somewhere.

**Comment by CaselIT** [comment]
If you want to send a PR to fix things until v2 is out we can merge and release fairly quickly

**Comment by mjpieters** [comment]
> If you want to send a PR to fix things until v2 is out we can merge and release fairly quickly

I traced this down to pyright not accepting that `AsyncSession` implements the `TypingAsyncSessionProtocol` type, because the signature of `no_autoflush` doesn't match:

```
Expression of type "Type[AsyncSession]" cannot be assigned to declared type "TypingAsyncSessionProtocol"
  "AsyncSession" is incompatible with protocol "TypingAsyncSessionProtocol"
  Type "Type[AsyncSession]" cannot be assigned to type "TypingAsyncSessionProtocol"
    "no_autoflush" is an incompatible type
      Type "(self: _TSessionNoIoTypingCommon@no_autoflush) -> ContextManager" cannot be assigned to type "(self: _TSharedSessionProtocol@no_autoflush) -> ContextManager"
        Parameter 1: type "_TSharedSessionProtocol@no_autoflush" cannot be assigned to type "_TSessionNoIoTypingCommon@no_autoflush"
          Type "_TSharedSessionProtocol@no_autoflush" cannot be assigned to type "_SessionNoIoTypingCommon[Unknown]"
        Function return type "ContextManager" is incompatible with type "ContextManager"
          "contextlib.AbstractContextManager" is incompatible with "contextlib.AbstractContextManager"
```

The issue could trivially be fixed if PEP 673 `typing.Self` was used there, but [mypy doesn't yet support PEP 673](https://github.com/python/mypy/issues/11871). :-(

However, I think I can at least make this fail for mypy as well with:

```
from typing import TYPE_CHECKING

from sqlalchemy.ext.asyncio import async_scoped_session
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import sessionmaker

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio.session import TypingAsyncSessionProtocol

engine = create_async_engine(...)
SessionType: type[TypingAsyncSessionProtocol] = AsyncSession
SM = sessionmaker(engine, class_=SessionType)

async_session = AsyncSession(engine)

as_session = async_scoped_session(SM, current_task)
```

This is an update to a single [`test/files/async_stuff.py` line](https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/dd0e6cf7e1c61cc1c25cd1d8d72c9f322fa73d90/test/files/async_stuff.py#L10), pulling out the `class_` argument into a separate type variable. Pyright / Pylance will complain about the `SessionType` assignment and again about passing `SM` on to `async_scoped_session()`, while MyPy only complains about the latter:

```
.../test/files/async_stuff.py:19: error: Argument 1 to "async_scope..._" has type "Callable[[KwArg(Any)], _AsyncSessionProtocol]"
```

**Comment by mjpieters** [comment]
Right, so the _simplest_ fix is to not use bound typevars for methods producing a contextmanager; for both `_SharedSessionProtocol` and `_SessionNoIoTypingCommon` use:

```python
    def no_autoflush(self: _M) -> ContextManager[_M]: ...
```

I was, however, wrong about my assessment that I could make mypy fail on the same issue; the error it produces when you use the `Type[TypingAsyncSessionProtocol]` annotation sticks even when Pylance is now happy with the annotations.

**Comment by mjpieters** [comment]
I've traced this to a Pyright issue with `@property` and `ContextManager`: https://github.com/microsoft/pyright/issues/4034

**Comment by CaselIT** [comment]
Thanks for debugging this. If you could provide a PR with the fix it would be great!

**Comment by mjpieters** [comment]
> Thanks for debugging this. If you could provide a PR with the fix it would be great!

It's an acknowledged pyright bug; it's in their court. The type definition is correct, the type checker is not, so no PR needed!

**Comment by CaselIT** [comment]
oh ok, good to know! thanks for looking into it! We can close then!
