### ISSUE TITLE
Cannot execute DDL construct

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy2-stubs#191]
**Describe the bug**
If I use a DDL construct, mypy conplains that it can't be executed. However using `.execute` raises a deprecation warning:

```
testscript.py:9: RemovedIn20Warning: The DDLElement.execute() method is considered legacy as of the 1.x series of SQLAlchemy and will be removed in 2.0. All statement execution in SQLAlchemy 2.0 is performed by the Connection.execute() method of Connection, or in the ORM by the Session.execute() method of Session. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```

**Expected behavior**
Mypy doesn't complain

**To Reproduce**

```py
from sqlalchemy.schema import CreateSequence, Sequence
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine

engine = create_engine("sqlite:////:memory:")
session = sessionmaker(bind=engine)()

construct = CreateSequence(Sequence("foo"))
try:
    construct.execute(bind=session)  # warning
    session.execute(construct)  # mypy
except:
    pass
```

**Error**

```
testscript.py:10: error: Argument "bind" to "execute" of "DDLElement" has incompatible type "Session"; expected "Union[Engine, Connection, None]"
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.27
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a19

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there  -

DDLElement.execute() is ancient history, while 1.4 still has it for very legacy code to use, generally it's gone and in 2.0 it's gone completely.    I'm -1 on taking any time to add this method to the stubs, so I would suggest just modernize the code before using the stubs.

**Comment by kasium** [comment]
Sorry if this was not clear, but `session.execute(construct)` fails with mypy. That was my point.
If that is not recommended, how should I then e,g, create sequences?

**Comment by zzzeek** [comment]
other than the fact that SQLite doesn't support sequences

**Comment by kasium** [comment]
@zzzeek I'm very sorry for this bad issue. I guess I got confused myself.
No mypy issue at all, maybe an outdated cache caused that, whatever.
