### ISSUE TITLE
declarative_base's constructor arg is optional

### ISSUE THREAD

**Issue by stefano-maggiolo** [sqlalchemy/sqlalchemy2-stubs#192]
**Describe the bug**
declarative_base's attribute "constructor" is [defined as non-optional](https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/main/sqlalchemy-stubs/orm/decl_api.pyi#L52), but SQLAlchemy documentation [says](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html#sqlalchemy.orm.declarative_base.params.constructor) it can be None

**Expected behavior**
constructor should be Optional

**Comment by CaselIT** [comment]
thanks for reporting. pr welcome!

**Comment by stefano-maggiolo** [comment]
PR sent. Not sure whether this is considered a "one line code fix requiring a test". If so, please point me to where this test should exists, thank you.

**Comment by CaselIT** [comment]
That should be fine, thanks
