### ISSUE TITLE
How to type hint a custom type?

### ISSUE THREAD

**Issue by danstewart** [sqlalchemy/sqlalchemy2-stubs#211]
We use GUID with MySQL by using a custom type inheriting from `TypeDecorator`, in short it will process incoming UUID hex strings into binary and outgoing binary back into the hex string (using [timeflake](https://pypi.org/project/timeflake/)).

When treating a GUID column as a string pylance complains:
> Expression of type "Column[GUID]" cannot be assigned to return type "str"
> "Column[GUID]" is incompatible with "str"

Here is the custom type:
```python
import timeflake
from sqlalchemy.types import BINARY, TypeDecorator


class GUID(TypeDecorator):
    """
    MySQL GUID type. Expects BINARY(16).
    """

    impl = BINARY
    cache_ok = True

    def load_dialect_impl(self, dialect):
        return dialect.type_descriptor(BINARY(16))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        elif isinstance(value, list):
            converted = []
            for item in value:
                if isinstance(item, timeflake.Timeflake):
                    converted.append(item.bytes)

                try:
                    hex = timeflake.parse(from_hex=item)
                    converted.append(hex.bytes)
                except KeyError:
                    pass

            return converted

        else:
            if isinstance(value, timeflake.Timeflake):
                return value.bytes

            try:
                return timeflake.parse(from_hex=value).bytes
            except KeyError:
                return None

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        else:
            try:
                return timeflake.parse(from_bytes=value).hex
            except KeyError:
                return None

    @property
    def python_type(self):
        return timeflake.Timeflake
```

Is there a way to type hint this as a `str` type?
I tried inheriting from `TypeDecorator[str]` but it didn't help.

**Versions**
 - OS: Ubuntu 20.04
 - Python: 3.10
 - SQLAlchemy: 1.4.29
 - mypy: NA
 - SQLAlchemy2-stubs: 0.0.2a20

Thanks :slightly_smiling_face:

**Comment by zzzeek** [comment]
in the stubs, TypeDecorator has nothing special going on, it has no given Python type unless you type it as `TypeDecorator[str]`.  I dont know where pylance would be seeing "str" otherwise, do you have the right stubs installed ?

**Comment by danstewart** [comment]
Sorry I didn't explain that part very well, I'm doing something like
```
def get_id() -> str:
  return model.id
```

But it complains `model.id` is not compatible with `str` - when it actually is a `str`.

I've noticed I'm having other issues too though so I think maybe I've broken something on my side, I'll close this and re-open if I manage to get the stubs working elsewhere.

Thanks
