### ISSUE TITLE
Accurate return types for sess.scalar() etc.

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy2-stubs#214]
Currently, it seems that `sess.scalar()` just returns `Any`, and `sess.scalars().all()` will end up with a `List[Any]` too:
https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/626d896cb24fd009f35e800fc42b6c50854884e9/sqlalchemy-stubs/ext/asyncio/session.pyi#L96
https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/626d896cb24fd009f35e800fc42b6c50854884e9/sqlalchemy-stubs/engine/result.pyi#L92

My expectation is that some simple code like:
```
stmt = sa.select(Foo).where(...)
foo = await sess.scalar(stmt)
```
would result in `foo` being inferred as `Foo`.

There is probably a lot of complexity and a reason it's not been done yet, but I don't see any other issue to track progress.

I guess for the simple cases, I'm expecting `select(foo)` to return something like `Select[Foo]`, and then scalar to be defined like `async def scalar(stmt: Select[T]) -> T:`.

**Comment by zzzeek** [comment]
this all works in 2.0 main which is typed inline.    See https://github.com/sqlalchemy/sqlalchemy/commit/ad11c482e2233f44e8747d4d5a2b17a995fff1fa .

**Comment by Dreamsorcerer** [comment]
Great, that's awesome. Didn't realise so much progress had already been made on v2.
