### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [sqlalchemy/sqlalchemy2-stubs#227]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/sqlalchemy2-stubs-feedstock

**Comment by CaselIT** [comment]
Thanks.

I personally have never published anything on conda forge, so I would not know where to begin.
You are welcome to publish it though!

**Comment by thewchan** [comment]
Hello! Sorry, let me clarify. The package has been published on Conda and it's working, but just wanting to know if you would like to be co-maintainer of it. It requires very little work as anytime an update is made on PyPI the bots will make a PR to update downstream as well. We can must merge the PR if all tests apsses.

**Comment by CaselIT** [comment]
oh ok! I don't think it's necessary for me to be a co-maintainer, but if you are looking for one I would be ok to help!

**Comment by thewchan** [comment]
No pressure at all; if you changed your mind and would live to join as a maintainer you know where to find me!
