### ISSUE TITLE
Error importing plugin "sqlalchemy.ext.mypy.plugin": cannot import name 'Optional' from 'mypy.plugin' 

### ISSUE THREAD

**Issue by iskyd** [sqlalchemy/sqlalchemy2-stubs#241]
**Describe the bug**
Error while running mypy on any file using sqlalchemy mypy plugin.

**To Reproduce**
Create a new virtualenv using Python 3.8
pip install sqlalchemy[mypy]==1.4

Create a simple mypy config (mypy.ini)
[mypy]
plugins = sqlalchemy.ext.mypy.plugin

Run mypy on any file
mypy --config-file=mypy.ini <file>

**Error**
Error importing plugin "sqlalchemy.ext.mypy.plugin": cannot import name 'Optional' from 'mypy.plugin' 

**Versions.**
 - OS: Linux Ubuntu 22.04
 - Python: 3.8
 - SQLAlchemy: 1.4
 - mypy: 0.991

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

please install one of the last slqlalchemy version of the 1.4 series.
The 1.4.0 is not supported at the moment
