### ISSUE TITLE
TypeEngine.with_variant should accept TypeEngine for type argument instances as well as Type[TypeEngine]

### ISSUE THREAD

**Issue by tapetersen** [sqlalchemy/sqlalchemy2-stubs#244]
**Describe the bug**
Documented usage for `TypeEngine.with_variant()` as here https://docs.sqlalchemy.org/en/14/core/type_basics.html#using-uppercase-and-backend-specific-types-for-multiple-backends
Uses an instance of a `TypeEngine` for the `type` argument like is usually done with `Column` for example. This gives a type error with current type stubs
**Expected behavior**
Documented usage with both an instance and a `TypeEngine` class directly should both work.
**To Reproduce**

```py
from sqlalchemy import Integer

# TypeEngine.with_variant should accept both a TypeEngine instance and the Concrete Type
Integer().with_variant(Integer, "mysql")
Integer().with_variant(Integer(), "mysql") # Fails type_checking before this change
# Also test Variant.with_variant
Integer().with_variant(Integer, "mysql").with_variant(Integer, "mysql")
Integer().with_variant(Integer, "mysql").with_variant(Integer(), "mysql")  # Fails type_checking before this change

```

**Versions.**
 - OS: Ubuntu 22.04
 - Python: cPython 3.10.6
 - SQLAlchemy: SQLAlchemy==1.4.41
 - mypy: Whatever runs with tox setup in this project
 - SQLAlchemy2-stubs: 0.0.2a27

**Comment by CaselIT** [comment]
thanks for reporting
