### ISSUE TITLE
MutableBase.coerce incorrectly returns None

### ISSUE THREAD

**Issue by huwcbjones** [sqlalchemy/sqlalchemy2-stubs#255]
**Describe the bug**
When subclassing Mutable and implementing coerce. I get a type error

**Expected behavior**
No error

**To Reproduce**
```py
from __future__ import annotations

from typing import Any

from sqlalchemy.ext.mutable import Mutable


class MWE(Mutable):

    @classmethod
    def coerce(cls, key: str, value: Any) -> str | None:
        if value is None:
            return None
        return str(value)

```

**Error**

```
mwe.py:11:5: error: Return type "Optional[str]" of "coerce" incompatible with return type "None" in supertype "MutableBase"  [override]
Found 1 error in 1 file (checked 1 source file)
```

**Versions.**
 - OS: All
 - Python: 3.9
 - SQLAlchemy: 1.4.46
 - mypy: 1.0.1
 - SQLAlchemy2-stubs: 0.0.2a34

**Additional Information**
The source code and docs imply that the return value of coerce is non-None.
See https://github.com/sqlalchemy/sqlalchemy/blob/b3bb55aaea9ee94e50f8db594d65c2bfcdb314ef/lib/sqlalchemy/ext/mutable.py#L51-L63

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. If you can send a PR it would speed up things
