### ISSUE TITLE
Cannot infer the type depending on the `Base` generate method.

### ISSUE THREAD

**Issue by barking-code** [sqlalchemy/sqlalchemy2-stubs#265]
**Describe the bug**

Try to generate `Base` in two ways. `declarative_base` can infer the type but `registry().generate_base()` is not.

```python
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
```

```python
from sqlalchemy.orm import registry

Base = registry().generate_base()
```

**Expected behavior**

It will be raised mypy error.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```

```py
from sqlalchemy import Column, Integer
from sqlalchemy.orm import registry

Base = registry().generate_base()  # declarative_base() does not raise the same error.


class Tester(Base):
    col1 = Column(Integer(), primary_key=True)


i: int = Tester.col1
```

**Error**

```
error: Variable "some_test.Base" is not valid as a type  [valid-type]
note: In class "Tester":
error: Invalid base class "Base"  [misc]
note: At top level:
error: Incompatible types in assignment (expression has type "Column[Integer]", variable has type "int")  [assignment]
```

**Versions.**
 - OS: Mac OS Ventura 13.0.1
 - Python: 3.10.14
 - SQLAlchemy: 1.4.49
 - mypy: 1.5.0
 - SQLAlchemy2-stubs: 0.0.2a38

**Additional context**

To use the mypy plugin, do I need to use methods from `sqlalchemy.ext`?
Is there no difference in how these two methods are used?

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Have you tried using `from sqlalchemy.orm import declarative_base`?

**Comment by barking-code** [comment]
> Hi,
> 
> Have you tried using `from sqlalchemy.orm import declarative_base`?

Hi, @CaselIT. It works very well.
I think the problem only occurred when using `registry().generate_base()`.

**Comment by CaselIT** [comment]
Ok,
It's unlikely that it will be fixed, since there stubs and the mypy plugin are all legacy and not needed for sqlalchemy v2

**Comment by barking-code** [comment]
@CaselIT 
Thank you for your comment. I have a question, can I use `declarative_base()` instead of `registry().generate_base()`?
I think those are perfectly the same if I use the same parameters.

**Comment by CaselIT** [comment]
Yes, they are exactly the same
