### ISSUE TITLE
`cascade` argument of `RelationshipProperty` does not allow passing string

### ISSUE THREAD

**Issue by layday** [sqlalchemy/sqlalchemy2-stubs#3]
I think this should be `Literal[False] | str`.

**Comment by zzzeek** [comment]
the stubs are 99% autogen at the moment and we'll have to do large passes across these systems to get all the args in.   PRs are welcome.

**Comment by layday** [comment]
Will do, I wasn't sure if you'd prefer these reported for you to investigate at your own pace or if you'd welcome contributions :)

**Comment by zzzeek** [comment]
I thnk 90% of the stubs are just boilerplate to fill in it's not like they make code crash or anything, maybe just stick to a few files at a time if you are sending PRs. thanks!
