### ISSUE TITLE
Missing `metadata` attribute on `Table` objects

### ISSUE THREAD

**Issue by linuxdaemon** [sqlalchemy/sqlalchemy2-stubs#60]
**Describe the bug**
It appears that the stubs are missing the `metadata` attribute on `Table` objects. When running mypy, I get `error: "Table" has no attribute "metadata"; maybe "tometadata" or "to_metadata"?  [attr-defined]`.

**Expected behavior**
The `metadata` field on `Table` objects should be defined, most likely as `Optional[MetaData]`.

**To Reproduce**
```py
from sqlalchemy import MetaData, Table, Column, String

meta = MetaData()
table = Table('table', meta, Column('column', String))

assert table.metadata is meta
```

**Error**

```
`error: "Table" has no attribute "metadata"; maybe "tometadata" or "to_metadata"?  [attr-defined]`.
```

**Versions.**
 - OS: Ubuntu 20.10
 - Python: 3.8.6
 - SQLAlchemy: 1.4.7
 - Database: N/A
 - DBAPI: N/A
 - SQLAlchemy2-stubs: 0.0.1a4
 - mypy: 0.812

**Comment by zzzeek** [comment]
would appaer to be resolved by #38.

**Comment by linuxdaemon** [comment]
I'm not seeing the attribute being added in that PR at all

**Comment by bryanforbes** [comment]
I just added the attribute in #38. Thanks for pointing that out!
