### ISSUE TITLE
filter and options methods of Query object aren't correctly detected

### ISSUE THREAD

**Issue by TilmanK** [sqlalchemy/sqlalchemy2-stubs#66]
Good Morning,

I was hoping my issue would be solved by #39 , sadly it isn't: you might want to have another look.

**Describe the bug**
Create a query using filter or options.

You will get 
`error: "filter" of "Query" does not return a value`
or
`error: "options" of "Query" does not return a value`

**Expected behavior**
No mypy message.

**To Reproduce**
Not a complete example, but I guess it's clear:
```py
session.query(User).filter(User.name == "John").options(joinedload(User.address)).all()
```

**Versions.**
 - OS:
 - Python: 3.8.6
 - SQLAlchemy: 1.4.9
 - Database:
 - DBAPI:

**Have a nice day!**
U2 :D

**Comment by zzzeek** [comment]
that would be this file which hasn't been worked on yet:

https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/master/sqlalchemy-stubs/orm/query.pyi
