### ISSUE TITLE
Datetime desc in Index results in arg-type error

### ISSUE THREAD

**Issue by 9dogs** [sqlalchemy/sqlalchemy2-stubs#82]
**Describe the bug**
mypy reports an error when `datetime_col.desc()` is used as an `Index` second argument; `datetime_col` (without `desc`) works as intended.

**Expected behavior**
mypy does not produce an error

**To Reproduce**
```py
from sqlalchemy import Column, DateTime, Integer, Index
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Model(Base):
    
    id = Column(Integer, primary_key=True)
    created_at = Column(DateTime)

    __tablename__ = 'model'
    __table_args__ = (
        # error: Argument 2 to "Index" has incompatible type "ClauseElement"; expected "ColumnClause[Any]"  [arg-type]
        Index('created_at_idx', created_at.desc()),
    )
```

**Error**

```
error: Argument 2 to "Index" has incompatible type "ClauseElement"; expected "ColumnClause[Any]"  [arg-type]
```

**Versions.**
 - OS: dockerized python:3.9.4-buster
 - Python: 3.9.4
 - SQLAlchemy: 1.4.12

**Have a nice day!**

**Comment by CaselIT** [comment]
Thanks for reporting

@bryanforbes was this fixed by #69?

**Comment by bryanforbes** [comment]
I don't think this is fixed

**Comment by MaicoTimmerman** [comment]
I think this is fixable by making `ColumnOperators` generic and letting the functions return `ColumnElement[_T]`. I've tried looking, but is there any use-case in which the `ColumnOperators` functions must return a `ClauseElement` as they currently do?
