### ISSUE TITLE
Publish to pypi as wheel

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy2-stubs#9]
**Is your feature request related to a problem? Please describe.**
Currently the package on pypi is published as a tarball. Installing usually requires first building the wheel and then installing

**Describe the solution you'd like**
Publish the package to pypi as a wheel

**Comment by CaselIT** [comment]
Hi,

This pachage has only stub files. What's the advantage of publishing wheels?

**Comment by layday** [comment]
wheel is the only distribution format that pip knows how to install. If there isn't a wheel, pip will build one from the sdist, locally.  If you've opted into PEP 517 (which you do simply by having a `pyproject.toml`), this involves creating a temporary directory, downloading and installing setuptools and wheels in it and then calling a couple of PEP 517 hooks in a subprocess to invoke `setup.py`. Publishing a wheel is energy-efficient ;)

**Comment by zzzeek** [comment]
twine is now replaced with tweel.sh:


```
#!/bin/bash

path=$1

tmp_dir=$(mktemp -d -t tweel-XXXXXXXXXX)

cp $path $tmp_dir/
pushd $tmp_dir/

fname=$( basename $path )

output=$( pip wheel -v ${fname} 2>&1 | grep -e "Created wheel" )

echo $output

if [[ $output =~ filename=([^ ]+) ]] ; then
    wheel=${BASH_REMATCH[1]}
    echo "uploading wheel ${wheel}"
    twine upload ${wheel}
else
    echo "couldn't find wheel file"
fi

popd
rm -fr $tmp_dir





```

**Comment by cancan101** [comment]
@zzzeek, What do you mean by that snippet? That issue has already been fixed? Or a fix coming soon?

**Comment by zzzeek** [comment]
the wheel should be on pypi
