### ISSUE TITLE
`AsyncEngine.begin()` returns `_trans_ctx` instead of expected `AsyncTransaction`

### ISSUE THREAD

**Issue by blazewicz** [sqlalchemy/sqlalchemy2-stubs#93]
`AsyncConnection.begin()` returns `AsyncTransaction`, like one would expect:

https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/e6ae4ccff041f202953e5a90dc157fd6710e3381/sqlalchemy-stubs/ext/asyncio/engine.pyi#L50

however, `AsyncEngine.begin()` returns `_trans_ctx`:

https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/e6ae4ccff041f202953e5a90dc157fd6710e3381/sqlalchemy-stubs/ext/asyncio/engine.pyi#L116

This leads to following errors, when user declares argument type to `AsyncTransaction`.

```
error: Argument "bar" to "foo" has incompatible type "_trans_ctx"; expected "AsyncTransaction"
```

**Comment by CaselIT** [comment]
Hi,

The typing itself is actually correct, see https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/asyncio/engine.py

But I'm not entirely sure if we could make the two begin behave more similarly wrt returned object. @zzzeek can't we return an async transaction from the `engine.begin`?

**Comment by CaselIT** [comment]
I think this is a won't fix for now
